services:
  dashboard:
    build:
      context: ./dashboard
    container_name: pj-dashboard
    expose:
      - "8080"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - dokploy-network

  backend:
    build:
      context: ./backend
    container_name: pj-backend
    expose:
      - "5000"
    volumes:
      - datos_procesados:/app/datos_procesados
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  datos_procesados:

networks:
  dokploy-network:
    external: true
